import mongoose from 'mongoose';

// Stores PDF highlight data and links each mark to a room, PDF, and user.
const annotationSchema = new mongoose.Schema({
    roomId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Room',
        required: true
    },
    pdfId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Pdf',
        required: true
    },
    userId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true
    },
    pageNumber: {
        type: Number,
        required: true
    },
    // Kept flexible for future mark types beyond highlights.
    type: {
        type: String,
        default: 'highlight'
    },
    // Holds coordinates, color, and author details generated by the frontend.
    annotationData: {
        type: mongoose.Schema.Types.Mixed,
        required: true
    }
}, { timestamps: true });

export default mongoose.model('Annotation', annotationSchema);
